plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/adityaadi/portfolio-website1/frontend/build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/adityaadi/portfolio-website1/frontend"
command = "yarn run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]